// Copyright (c) Dolittle. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.18.1
// source: Runtime/Client/BuildResult.proto

package client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuildResult_Type int32

const (
	BuildResult_INFORMATION BuildResult_Type = 0
	BuildResult_FAILURE     BuildResult_Type = 1
	BuildResult_ERROR       BuildResult_Type = 2
)

// Enum value maps for BuildResult_Type.
var (
	BuildResult_Type_name = map[int32]string{
		0: "INFORMATION",
		1: "FAILURE",
		2: "ERROR",
	}
	BuildResult_Type_value = map[string]int32{
		"INFORMATION": 0,
		"FAILURE":     1,
		"ERROR":       2,
	}
)

func (x BuildResult_Type) Enum() *BuildResult_Type {
	p := new(BuildResult_Type)
	*p = x
	return p
}

func (x BuildResult_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildResult_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_Runtime_Client_BuildResult_proto_enumTypes[0].Descriptor()
}

func (BuildResult_Type) Type() protoreflect.EnumType {
	return &file_Runtime_Client_BuildResult_proto_enumTypes[0]
}

func (x BuildResult_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildResult_Type.Descriptor instead.
func (BuildResult_Type) EnumDescriptor() ([]byte, []int) {
	return file_Runtime_Client_BuildResult_proto_rawDescGZIP(), []int{0, 0}
}

type BuildResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Type    BuildResult_Type `protobuf:"varint,2,opt,name=type,proto3,enum=dolittle.runtime.client.BuildResult_Type" json:"type,omitempty"`
}

func (x *BuildResult) Reset() {
	*x = BuildResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Runtime_Client_BuildResult_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildResult) ProtoMessage() {}

func (x *BuildResult) ProtoReflect() protoreflect.Message {
	mi := &file_Runtime_Client_BuildResult_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildResult.ProtoReflect.Descriptor instead.
func (*BuildResult) Descriptor() ([]byte, []int) {
	return file_Runtime_Client_BuildResult_proto_rawDescGZIP(), []int{0}
}

func (x *BuildResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BuildResult) GetType() BuildResult_Type {
	if x != nil {
		return x.Type
	}
	return BuildResult_INFORMATION
}

var File_Runtime_Client_BuildResult_proto protoreflect.FileDescriptor

var file_Runtime_Client_BuildResult_proto_rawDesc = []byte{
	0x0a, 0x20, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x2f, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x17, 0x64, 0x6f, 0x6c, 0x69, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x72, 0x75, 0x6e,
	0x74, 0x69, 0x6d, 0x65, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x97, 0x01, 0x0a, 0x0b,
	0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3d, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x64, 0x6f, 0x6c, 0x69, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x72,
	0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x42, 0x75,
	0x69, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x22, 0x2f, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b,
	0x49, 0x4e, 0x46, 0x4f, 0x52, 0x4d, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a,
	0x07, 0x46, 0x41, 0x49, 0x4c, 0x55, 0x52, 0x45, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52,
	0x52, 0x4f, 0x52, 0x10, 0x02, 0x42, 0x50, 0x5a, 0x2a, 0x67, 0x6f, 0x2e, 0x64, 0x6f, 0x6c, 0x69,
	0x74, 0x74, 0x6c, 0x65, 0x2e, 0x69, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x73, 0x2f, 0x76, 0x37, 0x2f, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2f, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0xaa, 0x02, 0x21, 0x44, 0x6f, 0x6c, 0x69, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x52,
	0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Runtime_Client_BuildResult_proto_rawDescOnce sync.Once
	file_Runtime_Client_BuildResult_proto_rawDescData = file_Runtime_Client_BuildResult_proto_rawDesc
)

func file_Runtime_Client_BuildResult_proto_rawDescGZIP() []byte {
	file_Runtime_Client_BuildResult_proto_rawDescOnce.Do(func() {
		file_Runtime_Client_BuildResult_proto_rawDescData = protoimpl.X.CompressGZIP(file_Runtime_Client_BuildResult_proto_rawDescData)
	})
	return file_Runtime_Client_BuildResult_proto_rawDescData
}

var file_Runtime_Client_BuildResult_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Runtime_Client_BuildResult_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Runtime_Client_BuildResult_proto_goTypes = []interface{}{
	(BuildResult_Type)(0), // 0: dolittle.runtime.client.BuildResult.Type
	(*BuildResult)(nil),   // 1: dolittle.runtime.client.BuildResult
}
var file_Runtime_Client_BuildResult_proto_depIdxs = []int32{
	0, // 0: dolittle.runtime.client.BuildResult.type:type_name -> dolittle.runtime.client.BuildResult.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Runtime_Client_BuildResult_proto_init() }
func file_Runtime_Client_BuildResult_proto_init() {
	if File_Runtime_Client_BuildResult_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Runtime_Client_BuildResult_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Runtime_Client_BuildResult_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Runtime_Client_BuildResult_proto_goTypes,
		DependencyIndexes: file_Runtime_Client_BuildResult_proto_depIdxs,
		EnumInfos:         file_Runtime_Client_BuildResult_proto_enumTypes,
		MessageInfos:      file_Runtime_Client_BuildResult_proto_msgTypes,
	}.Build()
	File_Runtime_Client_BuildResult_proto = out.File
	file_Runtime_Client_BuildResult_proto_rawDesc = nil
	file_Runtime_Client_BuildResult_proto_goTypes = nil
	file_Runtime_Client_BuildResult_proto_depIdxs = nil
}
