// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.18.1
// source: Runtime/Events.Processing/Processors.proto

package processing

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProcessorsClient is the client API for Processors service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProcessorsClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (Processors_ConnectClient, error)
}

type processorsClient struct {
	cc grpc.ClientConnInterface
}

func NewProcessorsClient(cc grpc.ClientConnInterface) ProcessorsClient {
	return &processorsClient{cc}
}

func (c *processorsClient) Connect(ctx context.Context, opts ...grpc.CallOption) (Processors_ConnectClient, error) {
	stream, err := c.cc.NewStream(ctx, &Processors_ServiceDesc.Streams[0], "/dolittle.runtime.events.processing.Processors/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &processorsConnectClient{stream}
	return x, nil
}

type Processors_ConnectClient interface {
	Send(*ProcessorClientToRuntimeMessage) error
	Recv() (*ProcessorRuntimeToClientMessage, error)
	grpc.ClientStream
}

type processorsConnectClient struct {
	grpc.ClientStream
}

func (x *processorsConnectClient) Send(m *ProcessorClientToRuntimeMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *processorsConnectClient) Recv() (*ProcessorRuntimeToClientMessage, error) {
	m := new(ProcessorRuntimeToClientMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ProcessorsServer is the server API for Processors service.
// All implementations must embed UnimplementedProcessorsServer
// for forward compatibility
type ProcessorsServer interface {
	Connect(Processors_ConnectServer) error
	mustEmbedUnimplementedProcessorsServer()
}

// UnimplementedProcessorsServer must be embedded to have forward compatible implementations.
type UnimplementedProcessorsServer struct {
}

func (UnimplementedProcessorsServer) Connect(Processors_ConnectServer) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedProcessorsServer) mustEmbedUnimplementedProcessorsServer() {}

// UnsafeProcessorsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProcessorsServer will
// result in compilation errors.
type UnsafeProcessorsServer interface {
	mustEmbedUnimplementedProcessorsServer()
}

func RegisterProcessorsServer(s grpc.ServiceRegistrar, srv ProcessorsServer) {
	s.RegisterService(&Processors_ServiceDesc, srv)
}

func _Processors_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProcessorsServer).Connect(&processorsConnectServer{stream})
}

type Processors_ConnectServer interface {
	Send(*ProcessorRuntimeToClientMessage) error
	Recv() (*ProcessorClientToRuntimeMessage, error)
	grpc.ServerStream
}

type processorsConnectServer struct {
	grpc.ServerStream
}

func (x *processorsConnectServer) Send(m *ProcessorRuntimeToClientMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *processorsConnectServer) Recv() (*ProcessorClientToRuntimeMessage, error) {
	m := new(ProcessorClientToRuntimeMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Processors_ServiceDesc is the grpc.ServiceDesc for Processors service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Processors_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dolittle.runtime.events.processing.Processors",
	HandlerType: (*ProcessorsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _Processors_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "Runtime/Events.Processing/Processors.proto",
}
