// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package embeddings

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EmbeddingsStoreClient is the client API for EmbeddingsStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmbeddingsStoreClient interface {
	GetOne(ctx context.Context, in *GetOneRequest, opts ...grpc.CallOption) (*GetOneResponse, error)
	GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllResponse, error)
}

type embeddingsStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewEmbeddingsStoreClient(cc grpc.ClientConnInterface) EmbeddingsStoreClient {
	return &embeddingsStoreClient{cc}
}

func (c *embeddingsStoreClient) GetOne(ctx context.Context, in *GetOneRequest, opts ...grpc.CallOption) (*GetOneResponse, error) {
	out := new(GetOneResponse)
	err := c.cc.Invoke(ctx, "/dolittle.runtime.embeddings.EmbeddingsStore/GetOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *embeddingsStoreClient) GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllResponse, error) {
	out := new(GetAllResponse)
	err := c.cc.Invoke(ctx, "/dolittle.runtime.embeddings.EmbeddingsStore/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmbeddingsStoreServer is the server API for EmbeddingsStore service.
// All implementations must embed UnimplementedEmbeddingsStoreServer
// for forward compatibility
type EmbeddingsStoreServer interface {
	GetOne(context.Context, *GetOneRequest) (*GetOneResponse, error)
	GetAll(context.Context, *GetAllRequest) (*GetAllResponse, error)
	mustEmbedUnimplementedEmbeddingsStoreServer()
}

// UnimplementedEmbeddingsStoreServer must be embedded to have forward compatible implementations.
type UnimplementedEmbeddingsStoreServer struct {
}

func (UnimplementedEmbeddingsStoreServer) GetOne(context.Context, *GetOneRequest) (*GetOneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOne not implemented")
}
func (UnimplementedEmbeddingsStoreServer) GetAll(context.Context, *GetAllRequest) (*GetAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedEmbeddingsStoreServer) mustEmbedUnimplementedEmbeddingsStoreServer() {}

// UnsafeEmbeddingsStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmbeddingsStoreServer will
// result in compilation errors.
type UnsafeEmbeddingsStoreServer interface {
	mustEmbedUnimplementedEmbeddingsStoreServer()
}

func RegisterEmbeddingsStoreServer(s grpc.ServiceRegistrar, srv EmbeddingsStoreServer) {
	s.RegisterService(&EmbeddingsStore_ServiceDesc, srv)
}

func _EmbeddingsStore_GetOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbeddingsStoreServer).GetOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dolittle.runtime.embeddings.EmbeddingsStore/GetOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbeddingsStoreServer).GetOne(ctx, req.(*GetOneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmbeddingsStore_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbeddingsStoreServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dolittle.runtime.embeddings.EmbeddingsStore/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbeddingsStoreServer).GetAll(ctx, req.(*GetAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmbeddingsStore_ServiceDesc is the grpc.ServiceDesc for EmbeddingsStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmbeddingsStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dolittle.runtime.embeddings.EmbeddingsStore",
	HandlerType: (*EmbeddingsStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOne",
			Handler:    _EmbeddingsStore_GetOne_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _EmbeddingsStore_GetAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Runtime/Embeddings/Store.proto",
}
